// Data
const anotherData = [
	{
		id: 1,
		company: "Zara",
		proName: "Cartoon Astronaut Shirts",
		img: "./images/p1.jpg",
		price: 1099,
	},
	{
		id: 2,
		company: "D & C",
		proName: "Linen Shirts",
		img: "./images/p2.jpg",
		price: 2099,
	},
	{
		id: 3,
		company: "Hugo Boss",
		proName: "Cuban Collar Shirts",
		img: "./images/p3.jpg",
		price: 1599,
	},
	{
		id: 4,
		company: "Calvin Klien",
		proName: "Hawaiian Shirts",
		img: "./images/p4.jpg",
		price: 2299,
	},
	{
		id: 5,
		company: "Burberry",
		proName: "Tropical Printed ",
		img: "./images/p5.jpg",
		price: 2299,
	},
	{
		id: 6,
		company: "Nike",
		proName: "Flannel Shirts",
		img: "./images/p6.jpg",
		price: 1999,
	},
	{
		id: 7,
		company: "Ralph Lauren ",
		proName: "Loose Fit",
		img: "./images/p7.jpg",
		price: 1899,
	},
	{
		id: 8,
		company: "Tommy Hilfiger",
		proName: "Oversize Tropical",
		img: "./images/p8.jpg",
		price: 2099,
	},
	{
		id: 9,
		company: "Zara",
		proName: "Half-Collared Shirts",
		img: "./images/n1.jpg",
		price: 1099,
	},
	{
		id: 10,
		company: "D&C",
		proName: "Linen Shirts",
		img: "./images/n2.jpg",
		price: 2099,
	},
	{
		id: 11,
		company: "Hugo Boss",
		proName: "Cuban Collar Shirts",
		img: "./images/n3.jpg",
		price: 1599,
	},
	{
		id: 12,
		company: "Calvin Klien",
		proName: "Hawaiian Shirts",
		img: "./images/n4.jpg",
		price: 2299,
	},
	{
		id: 13,
		company: "Burberry",
		proName: "OverSize",
		img: "./images/n5.jpg",
		price: 1299,
	},
	{
		id: 14,
		company: "Nike ",
		proName: "Shorts",
		img: "./images/n6.jpg",
		price: 899,
	},
	{
		id: 15,
		company: "Ralph Lauren ",
		proName: "Denim Shirts",
		img: "./images/n7.jpg",
		price: 1799,
	},
	{
		id: 16,
		company: "Biba",
		proName: "Printed Rayon V Neck ",
		img: "./images/n8.jpg",
		price: 1299,
	},
	{
		id: 17,
		company: "H&M",
		proName: "Oversize Tropical",
		img: "./images/w1.jpg",
		price: 1099,
	},
	{
		id: 18,
		company: " Fabindia",
		proName: "Printed V Neck Crepe",
		img: "./images/w2.jpg",
		price: 999,
	},
	{
		id: 19,
		company: "Biba",
		proName: "Printed Square Neck",
		img: "./images/w3.jpg",
		price: 1199,
	},
	{
		id: 20,
		company: "Allen Solly",
		proName: "Printed Round Neck Rayon ",
		img: "./images/w4.jpg",
		price: 1399,
	},
	{
		id: 21,
		company: "Allen Solly",
		proName: "Printed Round Neck Rayon ",
		img: "./images/w5.jpg",
		price: 1399,
	},
	{
		id: 22,
		company: "Allen Solly",
		proName: "Printed Round Neck Rayon ",
		img: "./images/w6.jpg",
		price: 1399,
	},
	{
		id: 23,
		company: "Allen Solly",
		proName: "Printed Round Neck Rayon ",
		img: "./images/w7.jpg",
		price: 1399,
	},
	{
		id: 24,
		company: "Allen Solly",
		proName: "Printed Round Neck Rayon ",
		img: "./images/w8.jpg",
		price: 1399,
	},
];
